### ISSUE TITLE
Default value for q

### ISSUE THREAD

**Issue by ctpelok77** [speckdavid/symk#2]
It looks like the default value for q is 1, and it can be misleading, as the configuration --search 'symq-bd(plan_selection=top_k(num_plans=1000))' will actually produce only optimal plans and stop when all optimal plans were found, even if the first 1000 plans include non-optimal plans. 
It seems like the default value for q should be infinity. Same for k (probably already is?).

**Comment by speckdavid** [comment]
This is indeed misleading. Especially because the default values are not the same for all configurations. The default values are now as follows:
- `plan_selection` must always be specified.
- The default value of `num_plans` is `infinity` for all `plan_selector`.
- The default value of `quality` is `infinity` for `symq-[fw/bw/bd]`.
- There is one exception for "ordinary" planning: `sym-[fw/bw/bd]` has a `plan_selection` of `top-k(num_plans=1)` by default.

I would also like to mention that if you are not interested in `quality` (= infinity), you can also directly run the configuration` symk-[fw/bw/bd]`. Although, I think that both configurations should be very similar in performance.

Finally, I am still not really satisfied with the parameter policy. Maybe it would be best to make `num_plans` and `quality` mandatory parameters without a default value to avoid confusion.

**Comment by ctpelok77** [comment]
- Making `quality` mandatory in top-k can be confusing as well. Same for `num_plans` in top-q. I would leave it with infinity default values there. 

- Why do you allow for specifying num_plans and quality in "ordinary" planning (sym-[fw/bw/bd]). 

-  > The default value of quality is infinity for symq-[fw/bw/bd]. 

Did you mean `symk`?

**Comment by speckdavid** [comment]
> * Making `quality` mandatory in top-k can be confusing as well. Same for `num_plans` in top-q. I would leave it with infinity default values there.

I agree.

> * Why do you allow for specifying num_plans and quality in "ordinary" planning (sym-[fw/bw/bd]).

It is probably best not to allow this. I will change it soon.

> * > The default value of quality is infinity for symq-[fw/bw/bd].
> 
> Did you mean `symk`?

At the moment these are two different search engines. Only symq has a quality parameter to set. Symk has an implicit default quality bound of infinity.  Yes, it is not really necessary to have two different search engines since the search is almost the same and symq already derives symk. I agree that this will make things clearer. I will address this after AAAI, as I don't think this is a really urgent issue at the moment?
