### ISSUE TITLE
Compilation and linking without -DUSE_LP=NO fails 

### ISSUE THREAD

**Issue by roveri-marco** [speckdavid/symk#3]
I've tried to compile your code on a linux ubutnu 20.04 machine where there is also installed coinor*
and it fails in the linking phase for undefined reference to gzclose and to other stuff. I managet to create the executable manually changing the link.txt script file generated by cmake by adding -lCoinUtils -lbz2 -lz -llapack -lblas -lm -lgfortran -lquadmath.

See the link.txt file in attach

[link.txt](https://github.com/speckdavid/symk/files/6616644/link.txt)

**Comment by speckdavid** [comment]
Thank you for reporting this issue. 

As a quick fix, it is probably indeed best to disable the USE_LP plugin in [src/search/CMakeLists.txt](../blob/master/src/search/CMakeLists.txt). 

Currently, the whole LP part is not used by symk and there is no problem to build and run symk without it. If you want to use LP-related code without symbolic search, I would recommend to use the latest [FastDownward](http://www.fast-downward.org/HomePage) version.

Fix:
I took a closer look at the issue and was able to reproduce it. It seems that this issue occurs due to a missing dependency to [zlib](https://www.zlib.net/). Also in the latest FastDownward release such a dependency was added and mentioned in the [LP installation procedure](http://www.fast-downward.org/LPBuildInstructions).

I added the zlib dependency (and SoPlex support) in the latest commit (084985e), which will hopefully fix the issue once zlib is installed (and all environment variables are set correctly, according to [LP installation procedure](http://www.fast-downward.org/LPBuildInstructions)). For Ubuntu this should be possible as follows.

`sudo apt install zlib1g-dev`

Let me know if there are any further issues or questions.

Best,
David
